version: "3.8"

services:
  web:
    image: ${DOCKER_REGISTRY}/credwave-web:${TAG}
    networks:
      - credwave_web
    ports:
      - target: 80
        published: 67
        mode: host
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

#t
networks:
  credwave_web:
    driver: overlay
