ALTER TABLE users
  ADD COLUMN IF NOT EXISTS promo_notif_7d       BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS promo_notif_3d       BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS promo_notif_1d       BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS promo_notif_expired  BOOLEAN NOT NULL DEFAULT FALSE;
